### ISSUE TITLE
Bundle install error for Rails 6.0.1

### ISSUE THREAD

**Issue by isubas** [plentz/lol_dba#113]
When trying to do `bundle install`, we receive an error like the following:

```
Downloading lol_dba-2.1.8 revealed dependencies not in the API or the lockfile
(actionpack (>= 3.0, < 6.0), activerecord (>= 3.0, < 6.0), railties (>= 3.0, < 6.0))
```
Used gem versions:

- rails 6.0.1
- lol_dba 2.1.8

The error seems to be caused by the `< 6.0` version constraint in the gemspec file.

**Comment by plentz** [comment]
I have made initial work at https://github.com/plentz/lol_dba/pull/114/, but there are some tests to be fixed before I can ship it.

**Comment by plentz** [comment]
`v2.2.0` is out 😉

**Comment by isubas** [comment]
Thank you @plentz
