### ISSUE TITLE
Undefined method constantize for Class

### ISSUE THREAD

**Issue by jeffblake** [plentz/lol_dba#46]
This gem seems to fail when an association `class_name` option is provided as a class rather than a string.

`Exception: undefined method `constantize' for #<Class:0x000001100c2040>`

**Comment by plentz** [comment]
@jeffblake could you provide an example? I don't understand what you mean by "as a class rather than a string"

**Comment by plentz** [comment]
and btw, it would be awesome if you can provide the full error message

**Comment by plentz** [comment]
please, test with `1.6.7`, it should be fixed :)
