### ISSUE TITLE
lol_dba doesn't work when you have multiple models with namespace

### ISSUE THREAD

**Issue by luizkowalski** [plentz/lol_dba#51]
I have a structure like that
![screen shot 2015-04-09 at 15 30 44](https://cloud.githubusercontent.com/assets/112706/7073966/6f37bcdc-decd-11e4-8ce3-5d7fe9e65a2f.png)
and I'm trying to runnin lol_dba on the classes that lives inside 'model' folder, not models on subfolders like 'tweek' and 'taste_profiler' but lol_dba tries to analyze classes from subfolders.
Is there a way to configure lol_dba?

edit: this is the stack trace http://pastebin.com/fi09pQan

**Comment by plentz** [comment]
@luizkowalski currently we don't have a way to do that. btw, we already [filter out](https://github.com/plentz/lol_dba/blob/master/lib/lol_dba.rb#L79) classes that doesn't have `ActiveRecord::Base` as an ancestors. What version of rails you're using? Can you create an test case([here](https://github.com/plentz/lol_dba/blob/master/spec/associations_index_spec.rb)) to reproduce your problem?

**Comment by luizkowalski** [comment]
Well, turns out my classes inside taste_profiler and tweek extendes another class which extends `ActiveRecord::Base` I'll try to reproduce it in another project. Also, I'm using Rails 4.2.1

**Comment by luizkowalski** [comment]
I ended up removing other classes which doest inherit from ActiveRecod::Base, but now I'm seeing this:
```
WARN: Unresolved specs during Gem::Specification.reset:
      activerecord (< 5.0, >= 3.0)
      actionpack (< 5.0, >= 3.0)
      railties (< 5.0, >= 3.0)
WARN: Clearing out unresolved specs.
```

**Comment by plentz** [comment]
I think you removed something that you shouldn't in the Gemfile. Can you double check it?

**Comment by luizkowalski** [comment]
I don't even touched my Gemfile...actually, lol_dba is on group :development, :test. Could this be te problem?

**Comment by luizkowalski** [comment]
Ok, that was the problem...Fixed and `Yey, no missing indexes found!` hahahaha
Closing this

**Comment by plentz** [comment]
@luizkowalski awesome! thanks for the feedback
