### ISSUE TITLE
Add Ruby version Runtime Dependencies

### ISSUE THREAD

**Issue by serg-kovalev** [plentz/lol_dba#52]
Hello,
You wrote that you still support `ruby 1.9.3`. But I found it hard to install the last `1.6.x` version of `lol_dba` using `gem 'lol_dba'` in my `Gemfile`.
```
Gem::InstallError: lol_dba requires Ruby version >= 2.0.0.
An error occurred while installing lol_dba (1.6.7), and Bundler cannot continue.
Make sure that `gem install lol_dba -v '1.6.7'` succeeds before bundling
```
Btw, I have successfully installed `1.5.x` version that is compatible with `ruby 1.9.3`.
In my `Gemfile` I have the runtime dependency for ruby. So I think it would be useful to update runtime dependency for this gem `lol_dba`.
Do you think?

**Comment by plentz** [comment]
@serg-kovalev you're right. since `1.6.5` I've increased the require ruby to 2.0(which was wrong, I should have released something like `1.7` or even `2.0`. I will do that today to avoid confusion.
