### ISSUE TITLE
Handle too long index name

### ISSUE THREAD

**Issue by westonganger** [plentz/lol_dba#56]
MySQL has a limitation on the length of the index name, not sure if it applies to other databases as well

Would be nice if it automatically shortened the name of the index

Its done like this with the extra name attribute

```
add_index :studies, ["user_id", "university_id", \
          "subject_name_id", "subject_type_id"], 
          :unique => true, :name => 'my_index'
```

**Comment by PirunSeng** [comment]
PostgreSQL also has this problem.

**Comment by Rakhi95** [comment]
try to give a meaningful name.

**Comment by sobrinho** [comment]
nowadays rails have an automated index name generation.

This can be closed, @plentz .
