### ISSUE TITLE
Polymorphic indexes invert field order and thought of as non-existing

### ISSUE THREAD

**Issue by nuclearspike** [plentz/lol_dba#60]
In my original migration, consider something like this:

```ruby
create_table :comments do |t|
t.references :commentable, polymorphic: true, index: true
end
```

This will create a "index_comments_on_commentable_type_and_commentable_id" (note the order of the fields)

When I run the gem, it will tell me that I should create an index on
`create_index :comments, [:commentable_id, :commentable_type]`

This is a handy tool, as a starting point. I only could really add 3 of the 13 or so indexes it proposed because the others either already existed in different field order, or the fields were not on the table.

**Comment by plentz** [comment]
@nuclearspike if you look at the source code, we always sort the index fields, so it makes sense. do you have any suggstions?

in the case of the fields that aren't on the table, can you create a test case to reproduce the problem? (I already fixed some of the problemas related with this, so make sure you're using the latest version ;) )

**Comment by plentz** [comment]
(#22 is the issue that I was talking about. btw, some of the problems are restrict to some rails versions due to differences in the way it returns metadata)
