### ISSUE TITLE
Weirdness with active_admin

### ISSUE THREAD

**Issue by yrral86** [plentz/lol_dba#62]
db:find_indexes gives me this:

    add_index :active_admin_comments, [:["resource_id", "resource_type"]]
    add_index :active_admin_comments, [:["author_id", "author_type"]]

which is obviously not valid ruby.

I already have these indexes defined:

    add_index "active_admin_comments", ["author_type", "author_id"], :name => "index_active_admin_comments_on_author_type_and_author_id"
    add_index "active_admin_comments", ["namespace"], :name => "index_active_admin_comments_on_namespace"
    add_index "active_admin_comments", ["resource_type", "resource_id"], :name => "index_admin_notes_on_resource_type_and_resource_id"

So I'm just going to remove those lines from the migration.

**Comment by plentz** [comment]
@yrral86 what version of lol_dba are you using? and what version of rails? thanks in advance :)

**Comment by yrral86** [comment]
Rail 3.2.21
lol_dba 2.0.0

**Comment by yrral86** [comment]
activeadmin 0.6.6

**Comment by plentz** [comment]
Hi @yrral86! I want to ask you another favor. Can you provide test cases for those classes as well? :heart:

**Comment by plentz** [comment]
@yrral86 I've just released `2.0.3` which should fix this problem. This was the same problem of #64 :)
