### ISSUE TITLE
has_and_belong_to_many with class_name option generates the wrong add_index migration.

### ISSUE THREAD

**Issue by joshuapinter** [plentz/lol_dba#65]
I have a `has_and_belong_to_many` (HABTM) between `User` and `Account`.

The association definitions are as follows: 

```ruby
class Account < ActiveRecord::Base
    has_and_belongs_to_many :users
end

class User < ActiveRecord::Base
    has_and_belongs_to_many :accessible_accounts, class_name: Account
end
```

The resulting index from `lol_dba` is: 

```ruby
add_index :accounts_users, [:accessible_account_id, :user_id]
```

Essentially it is ignoring the `class_name` option in the HABTM association definition.

I call the association from `User` to `Accounts`, `accessible_accounts` because I have a method called `accounts` that checks to see if they're a "super user" in which case they get access to all `Accounts`, otherwise, they only get access to the `Accounts` from the `accessible_accounts` relationship.

Thanks!

**Comment by plentz** [comment]
Hi @joshuapinter! Sorry for taking so long to reply! Can you test using the last version? [this test](https://github.com/plentz/lol_dba/blob/master/spec/associations_index_spec.rb#L75-L79) is exactly the example that you gave and works in all versions :)
