### ISSUE TITLE
Remove < 5.0 from gemspec restriction for rails support

### ISSUE THREAD

**Issue by hugocorbucci** [plentz/lol_dba#75]
The readme says that the gem is compatible with Rails 5.x but the gemspec restrictions ensure it cannot be 5 or above:
```
  s.add_dependency "activerecord", ">= 3.0", "< 5.0"
  s.add_dependency "actionpack", ">= 3.0", "< 5.0"
  s.add_dependency "railties", ">= 3.0", "< 5.0"
```

It might be enough to just change the restriction to less than 6.0

**Comment by plentz** [comment]
not really. but I'm working on it @ #73. keep an eye there :)

**Comment by plentz** [comment]
@hugocorbucci just released rails 5 with full support for rails 5(and a few more fixes) :)

**Comment by hugocorbucci** [comment]
@plentz is the ONE! 😄 👍 💯 🍷 🍻 🍸 🍾 
Thank you!
