### ISSUE TITLE
Output incorrectly reporting missing indexes (sort of)

### ISSUE THREAD

**Issue by chmurph2** [plentz/lol_dba#83]
After migrating some indexes that were reported missing by this gem, I ran it again, and while I was expecting this:

```
Yey, no missing indexes found!
```

I got this output instead:
```
* TIP: if you have a problem with the index name('index name too long') you can solve with the :name option. Something like :name => 'my_index'.
* run `rails g migration AddMissingIndexes` and add the following content:


    class AddMissingIndexes < ActiveRecord::Migration
      def change

      end
    end
```

This is because [this line](https://github.com/plentz/lol_dba/blob/master/lib/lol_dba.rb#L174) that checks for empty indexes/keys isn't actually empty at that point.  It's only [later](https://github.com/plentz/lol_dba/blob/master/lib/lol_dba.rb#L180) that those indexes in question are skipped [here](https://github.com/plentz/lol_dba/blob/master/lib/lol_dba.rb#L65).

I will open a PR to fix this problem.

**Comment by plentz** [comment]
fixed @ 2.1.2
