### ISSUE TITLE
Unresolved specs warning and show nothing in Rails 5.1

### ISSUE THREAD

**Issue by adamaiken89** [plentz/lol_dba#93]
When trying to run `lol_dba db:find_indexes` and the following warning is displayed but nothing related to keys are present.

```
WARN: Unresolved specs during Gem::Specification.reset:
      i18n (~> 0.7)
      rake (>= 0.8.7)
      thor (< 2.0, >= 0.18.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

Does anyone know how to solve this?

**Comment by plentz** [comment]
I've tried with the latest lol_dba and it didn't happen.
